ignore:

    - vulnerability: CVE-2021-20066 # nonsense, see issue tracker
      package:
        type: npm

    # Barking up the wrong tree ... that is, CVE creators aren't up to th
    # task of correctly filling in the information, especially about the
    # package ecosystems.
    - vulnerability: CVE-2017-18589 # rust, not npm package
      package:
        type: npm
    - vulnerability: CVE-2013-1779 # drupal, not npm package
      package:
        type: npm
    - vulnerability: CVE-2002-1647 # Slashdot website ffs, not npm package
      package:
        type: npm
    - vulnerability: CVE-2020-36634 # wrong util package, not npm package
      package:
        type: npm
    - vulnerability: CVE-2015-5237 # C, not Go module
      package:
        type: go-module
