// Let goreportcard check us.
// Code generated by gen_version; DO NOT EDIT.

package lxkns

// SemVersion is the semantic version string of the lxkns module.
const SemVersion = "0.21.12-13-g51067fb"
