// autogenerated from icon svg file "icons/Angryghost.svg", do not edit;
import * as React from 'react';
import { SvgIcon, SvgIconProps } from '@mui/material';
export const AngryghostIcon = (props: SvgIconProps) => <SvgIcon {...props}><path d="M12 2a9 9 0 0 0-9 9v11l3-3 3 3 3-3 3 3 3-3 3 3V11a9 9 0 0 0-9-9zM9 8a2 2 0 0 1 2 2 2 2 0 0 1-2 2 2 2 0 0 1-2-2 2 2 0 0 1 2-2zm6 0a2 2 0 0 1 2 2 2 2 0 0 1-2 2 2 2 0 0 1-2-2 2 2 0 0 1 2-2zm-7 5.586 2 2 2-2 2 2 2-2 2.707 2.707-1.414 1.414L16 16.414l-2 2-2-2-2 2-2-2-1.293 1.293-1.414-1.414L8 13.586z" /></SvgIcon>;
export default AngryghostIcon;