// autogenerated from icon svg file "icons/Children.svg", do not edit;
import * as React from 'react';
import { SvgIcon, SvgIconProps } from '@material-ui/core';
export const ChildrenIcon = (props: SvgIconProps) => <SvgIcon {...props}><path d="M0 0h24v24H0z" fill="none" /><path d="M8.852 6A3.5 3.5 0 019 7a3.5 3.5 0 01-.146 1H11v10h4.148A3.5 3.5 0 0115 17a3.5 3.5 0 01.146-1H13V8h2.148A3.5 3.5 0 0115 7a3.5 3.5 0 01.146-1H8.852z" fillOpacity={0.502} /><circle cx={5.5} cy={7} r={3.5} fillOpacity={0.502} /><circle cx={18.5} cy={7} r={3.5} /><circle cx={18.5} cy={17} r={3.5} /></SvgIcon>;
export default ChildrenIcon;