// autogenerated from icon svg file "icons/Children.svg", do not edit;
import * as React from 'react';
import { SvgIcon, SvgIconProps } from '@mui/material';
export const ChildrenIcon = (props: SvgIconProps) => <SvgIcon {...props}><path d="M0 0h24v24H0Z" /><path d="M8.852 6A3.5 3.5 0 0 1 9 7a3.5 3.5 0 0 1-.146 1H11v10h4.148A3.5 3.5 0 0 1 15 17a3.5 3.5 0 0 1 .146-1H13V8h2.148A3.5 3.5 0 0 1 15 7a3.5 3.5 0 0 1 .146-1H8.852z" /><circle cx={5.5} cy={7} r={3.5} /><circle cx={18.5} cy={7} r={3.5} /><circle cx={18.5} cy={17} r={3.5} /></SvgIcon>;
export default ChildrenIcon;