// autogenerated from icon svg file "icons/CPU.svg", do not edit;
import { SvgIcon, type SvgIconProps } from "@mui/material";
export const CPUIcon = (props: SvgIconProps) => <SvgIcon {...props}><path d="M9 15V9h6v6zm2-2h2v-2h-2Zm-2 8v-2H7q-.825 0-1.412-.587Q5 17.825 5 17v-2H3v-2h2v-2H3V9h2V7q0-.825.588-1.412Q6.175 5 7 5h2V3h2v2h2V3h2v2h2q.825 0 1.413.588Q19 6.175 19 7v2h2v2h-2v2h2v2h-2v2q0 .825-.587 1.413Q17.825 19 17 19h-2v2h-2v-2h-2v2zm8-4V7H7v10zm-5-5" /></SvgIcon>;
export default CPUIcon;