// autogenerated from icon svg file "icons/Download.svg", do not edit;
import { SvgIcon, type SvgIconProps } from "@mui/material";
export const DownloadIcon = (props: SvgIconProps) => <SvgIcon {...props}><path d="m12 16-5-5 1.4-1.45 2.6 2.6V4h2v8.15l2.6-2.6L17 11Zm-6 4q-.825 0-1.412-.587Q4 18.825 4 18v-3h2v3h12v-3h2v3q0 .825-.587 1.413Q18.825 20 18 20Z" /></SvgIcon>;
export default DownloadIcon;