// autogenerated from icon svg file "icons/Ghost.svg", do not edit;
import * as React from 'react';
import { SvgIcon, SvgIconProps } from '@mui/material';
export const GhostIcon = (props: SvgIconProps) => <SvgIcon {...props}><path d="M12 2a9 9 0 00-9 9v11l3-3 3 3 3-3 3 3 3-3 3 3V11a9 9 0 00-9-9zM9 8a2 2 0 012 2 2 2 0 01-2 2 2 2 0 01-2-2 2 2 0 012-2zm6 0a2 2 0 012 2 2 2 0 01-2 2 2 2 0 01-2-2 2 2 0 012-2z" /></SvgIcon>;
export default GhostIcon;