// autogenerated from icon svg file "icons/Ghost.svg", do not edit;
import { SvgIcon, type SvgIconProps } from "@mui/material";
export const GhostIcon = (props: SvgIconProps) => <SvgIcon {...props}><path d="M12 2a9 9 0 0 0-9 9v11l3-3 3 3 3-3 3 3 3-3 3 3V11a9 9 0 0 0-9-9M9 8a2 2 0 0 1 2 2 2 2 0 0 1-2 2 2 2 0 0 1-2-2 2 2 0 0 1 2-2m6 0a2 2 0 0 1 2 2 2 2 0 0 1-2 2 2 2 0 0 1-2-2 2 2 0 0 1 2-2" /></SvgIcon>;
export default GhostIcon;