// autogenerated from icon svg file "icons/Namespace.svg", do not edit;
import * as React from 'react';
import { SvgIcon, SvgIconProps } from '@material-ui/core';
export const NamespaceIcon = (props: SvgIconProps) => <SvgIcon {...props}><path d="M12.021 3a1 1 0 00-.337.05l-9 3A1 1 0 002 7v10a1 1 0 00.684.95l9 3a1 1 0 00.632 0l9-3A1 1 0 0022 17V7a1 1 0 00-.684-.95l-9-3a1 1 0 00-.295-.05zM12 5.055l6.504 2.168L12 9.398 5.496 7.223 12 5.055zM4 8.83l7 2.344v7.437L4 16.28V8.83zm16 0v7.45l-7 2.331v-7.437l7-2.344z" fontWeight={400} fontFamily="sans-serif" fillRule="evenodd" /></SvgIcon>;
export default NamespaceIcon;