// autogenerated from icon svg file "icons/Namespace.svg", do not edit;
import { SvgIcon, type SvgIconProps } from "@mui/material";
export const NamespaceIcon = (props: SvgIconProps) => <SvgIcon {...props}><path d="M12.021 3a1 1 0 0 0-.337.05l-9 3A1 1 0 0 0 2 7v10a1 1 0 0 0 .684.95l9 3a1 1 0 0 0 .632 0l9-3A1 1 0 0 0 22 17V7a1 1 0 0 0-.684-.95l-9-3a1 1 0 0 0-.295-.05M12 5.055l6.504 2.168L12 9.398 5.496 7.223zM4 8.83l7 2.344v7.437L4 16.28zm16 0v7.45l-7 2.331v-7.437z" /></SvgIcon>;
export default NamespaceIcon;