// autogenerated from icon svg file "icons/OffCPU.svg", do not edit;
import { SvgIcon, type SvgIconProps } from "@mui/material";
export const OffCPUIcon = (props: SvgIconProps) => <SvgIcon {...props}><path d="M2.1 2.1.686 3.514 5 7.828V9H3v2h2v2H3v2h2v2q0 .825.588 1.412Q6.176 19 7 19h2v2h2v-2h2v2h2v-2h1.172l4.312 4.313 1.416-1.415zM9 3v2H7.82l2 2H17v7.18l2 2V15h2v-2h-2v-2h2V9h-2V7q0-.824-.588-1.412A1.93 1.93 0 0 0 17 5h-2V3h-2v2h-2V3zm2.82 6L15 12.18V9zM7 9.828l2 2V15h3.172l2 2H7z" /></SvgIcon>;
export default OffCPUIcon;