// autogenerated from icon svg file "icons/Owner.svg", do not edit;
import * as React from 'react';
import { SvgIcon, SvgIconProps } from '@material-ui/core';
export const OwnerIcon = (props: SvgIconProps) => <SvgIcon {...props}><path d="M5 16L3 5l5 5 4-6 4 6 5-5-2 11H5M19 19c0 .6-.4 1-1 1H6c-.6 0-1-.4-1-1v-1h14z" /></SvgIcon>;
export default OwnerIcon;