// autogenerated from icon svg file "icons/Pinned.svg", do not edit;
import { SvgIcon, type SvgIconProps } from "@mui/material";
export const PinnedIcon = (props: SvgIconProps) => <SvgIcon {...props}><path fillRule="evenodd" d="m15.58 12.726 2.5-4.33.867.5c.476.275 1.09.11 1.366-.366a1.003 1.003 0 0 0-.366-1.366l-8.66-5a1.003 1.003 0 0 0-1.367.366 1.003 1.003 0 0 0 .366 1.366l.866.5-2.5 4.33a2.996 2.996 0 0 1-4.098 1.098l-1 1.732 5.17 2.985-3.5 6.062.366 1.366 1.366-.366 3.5-6.062 5.223 3.015 1-1.732a2.996 2.996 0 0 1-1.098-4.098" /></SvgIcon>;
export default PinnedIcon;