// autogenerated from icon svg file "icons/Pinned.svg", do not edit;
import { SvgIcon, type SvgIconProps } from "@mui/material";
export const PinnedIcon = (props: SvgIconProps) => <SvgIcon {...props}><path d="m14.397 15.05 4-6.928.866.5 1-1.732-8.66-5-1 1.732.866.5-4 6.928-2.732.732-1 1.732 4.503 2.6-3 5.196 1.386.8 3-5.196 4.503 2.6 1-1.732z" /></SvgIcon>;
export default PinnedIcon;