// autogenerated from icon svg file "icons/Root.svg", do not edit;
import * as React from 'react';
import { SvgIcon, SvgIconProps } from '@mui/material';
export const RootIcon = (props: SvgIconProps) => <SvgIcon {...props}><path d="M12 5a4 4 0 0 1 4 4 4 4 0 0 1-4 4 4 4 0 0 1-4-4 4 4 0 0 1 4-4m0 10c4.42 0 8 1.79 8 4v2H4v-2c0-2.21 3.58-4 8-4z" /><path d="M10 5.585C8.924 5.255 6.746 4 6 3c0 2 1.037 4.271 2.492 5.271ZM14 5.585C15.076 5.255 17.254 4 18 3c0 2-1.037 4.271-2.492 5.271Z" /></SvgIcon>;
export default RootIcon;