// autogenerated from icon svg file "icons/Thread.svg", do not edit;
import * as React from 'react';
import { SvgIcon, SvgIconProps } from '@mui/material';
export const ThreadIcon = (props: SvgIconProps) => <SvgIcon {...props}><path d="M0 0h24v24H0z" fill="none" /><path d="M3 3v3a1 1 0 001 1h10a1 1 0 001-1V3H3zm1 1h10v2H4V4zm1 4v2h8v-.5c1 0 2.723.01 3.994.357.636.174 1.137.434 1.39.733.255.298.352.62.141 1.252a2.278 2.278 0 00.06 1.623c.2.465.52.832.847 1.12a5.467 5.467 0 001.375.876l.386-.922s-.594-.254-1.1-.701c-.252-.224-.47-.49-.587-.766a1.198 1.198 0 01-.031-.914c.29-.868.136-1.671-.329-2.217-.464-.545-1.15-.847-1.89-1.048C15.777 8.489 14 8.5 13 8.5V8H5zm0 3v2h8v-2H5zm0 3v2h8v-2H5zm-1 3a1 1 0 00-1 1v3h12v-3a1 1 0 00-1-1H4zm0 1h10v2H4v-2z" /></SvgIcon>;
export default ThreadIcon;