version: '2.4'
services:
    reverse:
        image: nginx:1.20
        ports: 
            - "15010:15010"
        volumes:
            - ./nginx.conf:/etc/nginx/nginx.conf
        networks: 
            # Ensure to use the network for the project "lxkns" as opposed to
            # our own project-specific one. This way træfik can successfully
            # forward traffic to our lxkns service.
            - default

networks:
    default:
        # Sticking with defaults, yet forcing the network name, allows us to
        # either attach to an already created default network from the "lxkns"
        # composer project or create it in case we're started earlier than the
        # lxkns project and its default network hasn't ever been created before.
        name: lxkns_default