// autogenerated from icon svg file "icons/propagation/Peer.svg", do not edit;
import { SvgIcon, type SvgIconProps } from "@mui/material";
export const PeerIcon = (props: SvgIconProps) => <SvgIcon {...props}><path fill="none" d="M0 0h24v24H0z" /><path d="M5.54 8.46 2 12l3.54 3.54 1.76-1.77L5.54 12l1.76-1.77Zm6.46 10-1.77-1.76-1.77 1.76L12 22l3.54-3.54-1.77-1.76Zm6.46-10-1.76 1.77L18.46 12l-1.76 1.77 1.76 1.77L22 12Z" /><circle cx={12} cy={12} r={3} /></SvgIcon>;
export default PeerIcon;