// autogenerated from icon svg file "icons/propagation/Slave.svg", do not edit;
import * as React from 'react';
import { SvgIcon, SvgIconProps } from '@mui/material';
export const SlaveIcon = (props: SvgIconProps) => <SvgIcon {...props}><path fill="none" d="M0 0h24v24H0V0z" /><path d="m12 3.755-1.77-1.76-1.77 1.76L12 7.295l3.54-3.54-1.77-1.76z" /><circle cx={12} cy={12} r={3} /></SvgIcon>;
export default SlaveIcon;