// autogenerated from icon svg file "icons/propagation/Unbindable.svg", do not edit;
import * as React from 'react';
import { SvgIcon, SvgIconProps } from '@mui/material';
export const UnbindableIcon = (props: SvgIconProps) => <SvgIcon {...props}><path d="M11.957 4a8 8 0 0 0-8 8 8 8 0 0 0 8 8 8 8 0 0 0 8-8 8 8 0 0 0-8-8zM12 6a6 6 0 0 1 6 6 6 6 0 0 1-6 6 6 6 0 0 1-6-6 6 6 0 0 1 6-6zm0 3a3 3 0 0 0-3 3 3 3 0 0 0 3 3 3 3 0 0 0 3-3 3 3 0 0 0-3-3z" /><path fill="none" d="M0 0h24v24H0V0z" /></SvgIcon>;
export default UnbindableIcon;