// autogenerated from icon svg file "icons/propagation/Unbindable.svg", do not edit;
import * as React from 'react';
import { SvgIcon, SvgIconProps } from '@mui/material';
export const UnbindableIcon = (props: SvgIconProps) => <SvgIcon {...props}><path d="M11.957 4a8 8 0 00-8 8 8 8 0 008 8 8 8 0 008-8 8 8 0 00-8-8zM12 6a6 6 0 016 6 6 6 0 01-6 6 6 6 0 01-6-6 6 6 0 016-6zm0 3a3 3 0 00-3 3 3 3 0 003 3 3 3 0 003-3 3 3 0 00-3-3z" /><path d="M0 0h24v24H0V0z" fill="none" /></SvgIcon>;
export default UnbindableIcon;