// autogenerated from icon svg file "icons/containers/Container.svg", do not edit;
import { SvgIcon, type SvgIconProps } from "@mui/material";
export const ContainerIcon = (props: SvgIconProps) => <SvgIcon {...props}><path d="M9.982 2a2 2 0 0 0-1.091.336l-6 4A2 2 0 0 0 2 8v9a2 2 0 0 0 1.367 1.896l6 2a2 2 0 0 0 1.026.065l10-2A2 2 0 0 0 22 17V7a2 2 0 0 0-1.426-1.916l-10-3A2 2 0 0 0 9.982 2M11 4.3 20 7v10l-9 1.8zm-2 .366v14L4 17V8zM6 8v8h1V8z" /></SvgIcon>;
export default ContainerIcon;