// autogenerated from icon svg file "icons/containers/Container.svg", do not edit;
import * as React from 'react';
import { SvgIcon, SvgIconProps } from '@mui/material';
export const ContainerIcon = (props: SvgIconProps) => <SvgIcon {...props}><path d="M9.982 2a2 2 0 00-1.091.336l-6 4A2 2 0 002 8v9a2 2 0 001.367 1.896l6 2a2 2 0 001.026.065l10-2A2 2 0 0022 17V7a2 2 0 00-1.426-1.916l-10-3A2 2 0 009.982 2zM11 4.3L20 7v10l-9 1.8V4.3zm-2 .366v14L4 17V8l5-3.334zM6 8v8h1V8H6z" /></SvgIcon>;
export default ContainerIcon;