// autogenerated from icon svg file "icons/containers/Containerd.svg", do not edit;
import * as React from 'react';
import { SvgIcon, SvgIconProps } from '@mui/material';
export const ContainerdIcon = (props: SvgIconProps) => <SvgIcon {...props}><path d="M6 3v18h13V3Zm9 4h2v12H8v-9h7zm-5 5v5h5v-5z" /></SvgIcon>;
export default ContainerdIcon;