// autogenerated from icon svg file "icons/containers/IEApp.svg", do not edit;
import * as React from 'react';
import { SvgIcon, SvgIconProps } from '@mui/material';
export const IEAppIcon = (props: SvgIconProps) => <SvgIcon {...props}><path d="M18 1l-5 5 5 5 5-5-5-5zM3 6v15h15v-7.172L10.172 6H3z" /></SvgIcon>;
export default IEAppIcon;