// autogenerated from icon svg file "icons/containers/IERuntime.svg", do not edit;
import * as React from 'react';
import { SvgIcon, SvgIconProps } from '@mui/material';
export const IERuntimeIcon = (props: SvgIconProps) => <SvgIcon {...props}><path d="M20 5l-3 3 3 3 3-3-3-3zM2 8v10h2V8H2zm3 0v10h3V8H5zm4 0v10h1v-1h1v1h1v-1h1v1h1v-1h1v1h5v-4.781L14.781 8H9z" /></SvgIcon>;
export default IERuntimeIcon;