// autogenerated from icon svg file "icons/containers/IERuntime.svg", do not edit;
import { SvgIcon, type SvgIconProps } from "@mui/material";
export const IERuntimeIcon = (props: SvgIconProps) => <SvgIcon {...props}><path d="m20 5-3 3 3 3 3-3zM2 8v10h2V8zm3 0v10h3V8zm4 0v10h1v-1h1v1h1v-1h1v1h1v-1h1v1h5v-4.781L14.781 8z" /></SvgIcon>;
export default IERuntimeIcon;