// autogenerated from icon svg file "icons/containers/K8sPod.svg", do not edit;
import { SvgIcon, type SvgIconProps } from "@mui/material";
export const K8sPodIcon = (props: SvgIconProps) => <SvgIcon {...props}><path d="M12 2.964 4.484 6.537l-1.856 8.03 5.201 6.437h8.342l5.201-6.437-1.856-8.03Zm-.034 3.873 5.069 1.625-5.07 2.104-5.068-2.104Zm-5.07 2.885 4.485 1.863v5.979L6.897 15.7Zm10.139 0v5.979l-4.485 1.863v-5.979z" /></SvgIcon>;
export default K8sPodIcon;