// autogenerated from icon svg file "icons/containers/Kind.svg", do not edit;
import { SvgIcon, type SvgIconProps } from "@mui/material";
export const KindIcon = (props: SvgIconProps) => <SvgIcon {...props}><path d="M3 4c-.554 0-1 .446-1 1v14c0 .554.446 1 1 1h14c2 0 3-6 4-6h1v-4h-1c-1 0-2-6-4-6zm1 2h13c2 0 2 5 4 5v2c-2 0-2 5-4 5h-1l1-4h-2v-2h-3v-2h-2v2H9v2H8v-3H6v3H5l1 4H4zm9.996 3.652-.508 1.934 2.903.762.507-1.934z" /></SvgIcon>;
export default KindIcon;