version: '2.4'
services: 
    lxkns:
        image: lxkns:latest
        read_only: true
        mem_limit: 32mb
        command:
            - "/lxkns"
            - "--initialcgroup"
        ports:
            - "5010:5010"
        user: "65534"
        # Clean all default capabilities Docker might otherwise grant us and
        # several of them we don't need; add only those capabilities we really
        # need, such as CAP_WORLD_DOMINATION.
        cap_drop:
            - ALL
        cap_add:
            - SYS_ADMIN       # change namespaces
            - SYS_CHROOT      # change mount namespaces
            - SYS_PTRACE      # access nsfs namespace information
            - DAC_READ_SEARCH # for fully discovering bind-mounted namespaces
            - DAC_OVERRIDE    # for accessing the containerd API socket
        # We need the full PID view for correct scanning.
        pid: host
        # when operating in a "pure" unified cgroup hierarchy without any traces
        # of v1+v2 hybrid hierarchies, then Docker now defaults to creating
        # private cgroup namespaces for containers. Of course, this is exactly
        # what defeats the purpose of system diagnosis containers, such as
        # lxkns. Unfortunately, the compose definition yet doesn't support
        # setting the cgroup namespace mode "private" or "host" (it simply
        # doesn't exist).
        #
        # cgroup: host
