# Enforce that the kindest/base tag to build from must always be specified.
ARG KINDEST_BASE_TAG

FROM kindest/base:${KINDEST_BASE_TAG}

# Complete and also modify the kindest/base configuration.
COPY files/ /
