#!/bin/sh
set -e
TIMEOUT=3m
echo "starting tests... 🦗 🦗 🦗"
echo "PHASE I: as root 🤪"
go test -v -timeout ${TIMEOUT} -exec sudo ./...
echo "PHASE II: as non-root user 😇"
go test -v -timeout ${TIMEOUT} ./...
