# requires docker compose plugin (=v2)
#
# wget -q -O - https://github.com/thediveo/lxkns/raw/master/deployments/wget/docker-compose.yaml | docker compose -f - up
name: lxkns
services: 
    lxkns:
        image: ghcr.io/thediveo/lxkns
        pull_policy: always
        restart: 'unless-stopped'
        read_only: true
        command:
            - "/lxkns"
            - "--debug"
        ports:
            - "5010:5010"
        user: "65534"
        security_opt:
            - apparmor:unconfined # cannot load a remote profile
        # Clean all default capabilities Docker might otherwise grant us and
        # several of them we don't need; add only those capabilities we really
        # need, such as CAP_WORLD_DOMINATION.
        cap_drop:
            - ALL
        cap_add:
            - SYS_ADMIN       # change namespaces
            - SYS_CHROOT      # change mount namespaces
            - SYS_PTRACE      # access nsfs namespace information
            - DAC_READ_SEARCH # for fully discovering bind-mounted namespaces
            - DAC_OVERRIDE    # for accessing the containerd API socket
        # We need the full PID view for correct scanning.
        pid: host
        # when operating in a "pure" unified cgroup hierarchy without any traces
        # of v1+v2 hybrid hierarchies, then Docker now defaults to creating
        # private cgroup namespaces for containers. Of course, this is exactly
        # what defeats the purpose of system diagnosis containers, such as
        # lxkns.
        cgroup: host
