name: build and test
on:
  push:
    branches:
    - master
    - feature/test-webui

jobs:

  buildandtest:
    name: Build and Test on Go ${{matrix.go}}
    runs-on: ubuntu-20.04
    strategy:
      matrix:
        go: ['1.16', '1.14']
    steps:
    - name: Set up Go ${{matrix.go}}
      uses: actions/setup-go@v1
      with:
        go-version: ${{matrix.go}}
      id: go

    - name: Check out code into the Go module directory
      uses: actions/checkout@v2

    - name: Get dependencies
      run: go get -v -t -d ./...

    - name: Test Go packages
      run: sudo go test -v ./... && go test -v ./...

  testwebapp:
    name: Test web ui of lxkns service
    runs-on: ubuntu-20.04
    needs: buildandtest
    steps:
    - name: Check out code
      uses: actions/checkout@v2

    - name: Test WebUI units and end-to-end
      run: (cd web/lxkns && yarn install) && make citestapp
